//! Deterministic extension runtime primitives.
//!
//! This module provides a first-class extension surface similar to modern
//! editor systems while preserving deterministic transaction generation.

use serde::Deserialize;
use serde::Serialize;

use crate::Document;
use crate::EditorEvent;
use crate::Selection;
use crate::operation::Transaction;

/// Metadata attached to a transaction generated by the extension runtime.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct TransactionMeta {
	origin: String,
	command: Option<String>,
	input_rule: Option<String>,
	replayable: bool,
}

impl TransactionMeta {
	/// Create metadata with a required origin identifier.
	#[must_use]
	pub fn new(origin: impl Into<String>) -> Self {
		Self {
			origin: origin.into(),
			command: None,
			input_rule: None,
			replayable: true,
		}
	}

	/// Optional command identifier.
	#[must_use]
	pub fn with_command(mut self, command: impl Into<String>) -> Self {
		self.command = Some(command.into());
		self
	}

	/// Optional input rule identifier.
	#[must_use]
	pub fn with_input_rule(mut self, input_rule: impl Into<String>) -> Self {
		self.input_rule = Some(input_rule.into());
		self
	}

	/// Mark whether the transaction should be persisted for replay.
	#[must_use]
	pub fn with_replayable(mut self, replayable: bool) -> Self {
		self.replayable = replayable;
		self
	}

	#[must_use]
	pub fn origin(&self) -> &str {
		&self.origin
	}

	#[must_use]
	pub fn command(&self) -> Option<&str> {
		self.command.as_deref()
	}

	#[must_use]
	pub fn input_rule(&self) -> Option<&str> {
		self.input_rule.as_deref()
	}

	#[must_use]
	pub fn replayable(&self) -> bool {
		self.replayable
	}
}

/// An executable command contributed by an extension.
pub trait Command: Send + Sync {
	fn id(&self) -> &'static str;
	fn execute(
		&self,
		doc: &Document,
		selection: Selection,
		event: &EditorEvent,
	) -> Option<Transaction>;
}

/// A text/input rule that may emit a transaction when its condition matches.
pub trait InputRule: Send + Sync {
	fn id(&self) -> &'static str;
	fn on_event(
		&self,
		doc: &Document,
		selection: Selection,
		event: &EditorEvent,
	) -> Option<Transaction>;
}

/// A hook invoked around transaction dispatch.
pub trait TransactionHook: Send + Sync {
	fn id(&self) -> &'static str;
	fn before_apply(
		&self,
		_doc: &Document,
		_meta: &TransactionMeta,
		tx: Transaction,
	) -> Transaction {
		tx
	}
	fn after_apply(&self, _doc: &Document, _meta: &TransactionMeta, _tx: &Transaction) {}
}

/// Extension bundle definition.
pub trait Extension: Send + Sync {
	fn id(&self) -> &'static str;
	fn priority(&self) -> i32 {
		0
	}
	fn commands(&self) -> Vec<Box<dyn Command>> {
		Vec::new()
	}
	fn input_rules(&self) -> Vec<Box<dyn InputRule>> {
		Vec::new()
	}
	fn transaction_hooks(&self) -> Vec<Box<dyn TransactionHook>> {
		Vec::new()
	}
}

/// A transaction emitted by the runtime with deterministic metadata.
#[derive(Debug, Clone, PartialEq)]
pub struct RuntimeTransaction {
	pub meta: TransactionMeta,
	pub transaction: Transaction,
}

/// Deterministic extension runtime coordinator.
pub struct ExtensionRuntime {
	commands: Vec<CommandEntry>,
	input_rules: Vec<InputRuleEntry>,
	hooks: Vec<HookEntry>,
}

struct CommandEntry {
	priority: i32,
	extension_id: &'static str,
	command: Box<dyn Command>,
}

struct InputRuleEntry {
	priority: i32,
	extension_id: &'static str,
	rule: Box<dyn InputRule>,
}

struct HookEntry {
	priority: i32,
	extension_id: &'static str,
	hook: Box<dyn TransactionHook>,
}

impl ExtensionRuntime {
	#[must_use]
	pub fn new(mut extensions: Vec<Box<dyn Extension>>) -> Self {
		extensions.sort_by(|a, b| {
			b.priority()
				.cmp(&a.priority())
				.then_with(|| a.id().cmp(b.id()))
		});

		let mut commands = Vec::new();
		let mut input_rules = Vec::new();
		let mut hooks = Vec::new();

		for extension in extensions {
			let extension_id = extension.id();
			let priority = extension.priority();

			for command in extension.commands() {
				commands.push(CommandEntry {
					priority,
					extension_id,
					command,
				});
			}

			for rule in extension.input_rules() {
				input_rules.push(InputRuleEntry {
					priority,
					extension_id,
					rule,
				});
			}

			for hook in extension.transaction_hooks() {
				hooks.push(HookEntry {
					priority,
					extension_id,
					hook,
				});
			}
		}

		commands.sort_by(|a, b| {
			b.priority
				.cmp(&a.priority)
				.then_with(|| a.extension_id.cmp(b.extension_id))
				.then_with(|| a.command.id().cmp(b.command.id()))
		});
		input_rules.sort_by(|a, b| {
			b.priority
				.cmp(&a.priority)
				.then_with(|| a.extension_id.cmp(b.extension_id))
				.then_with(|| a.rule.id().cmp(b.rule.id()))
		});
		hooks.sort_by(|a, b| {
			b.priority
				.cmp(&a.priority)
				.then_with(|| a.extension_id.cmp(b.extension_id))
				.then_with(|| a.hook.id().cmp(b.hook.id()))
		});

		Self {
			commands,
			input_rules,
			hooks,
		}
	}

	pub fn run_commands(
		&self,
		doc: &Document,
		selection: Selection,
		event: &EditorEvent,
	) -> Option<RuntimeTransaction> {
		for entry in &self.commands {
			if let Some(transaction) = entry.command.execute(doc, selection, event) {
				return Some(RuntimeTransaction {
					meta: TransactionMeta::new(entry.extension_id).with_command(entry.command.id()),
					transaction,
				});
			}
		}
		None
	}

	pub fn run_input_rules(
		&self,
		doc: &Document,
		selection: Selection,
		event: &EditorEvent,
	) -> Option<RuntimeTransaction> {
		for entry in &self.input_rules {
			if let Some(transaction) = entry.rule.on_event(doc, selection, event) {
				return Some(RuntimeTransaction {
					meta: TransactionMeta::new(entry.extension_id).with_input_rule(entry.rule.id()),
					transaction,
				});
			}
		}
		None
	}

	/// Resolve transaction transforms from `before_apply` hooks in deterministic order.
	#[must_use]
	pub fn resolve_before_hooks(
		&self,
		doc: &Document,
		meta: &TransactionMeta,
		mut transaction: Transaction,
	) -> Transaction {
		for entry in &self.hooks {
			transaction = entry.hook.before_apply(doc, meta, transaction);
		}
		transaction
	}

	/// Run `after_apply` hooks in deterministic order.
	pub fn run_after_hooks(
		&self,
		doc: &Document,
		meta: &TransactionMeta,
		transaction: &Transaction,
	) {
		for entry in &self.hooks {
			entry.hook.after_apply(doc, meta, transaction);
		}
	}

	pub fn apply_with_hooks(&self, doc: &mut Document, runtime_tx: RuntimeTransaction) {
		let transaction = self.resolve_before_hooks(doc, &runtime_tx.meta, runtime_tx.transaction);
		transaction.apply(doc);
		self.run_after_hooks(doc, &runtime_tx.meta, &transaction);
	}
}

#[cfg(test)]
mod tests {
	use std::sync::Arc;
	use std::sync::Mutex;

	use super::*;
	use crate::Position;
	use crate::operation::Operation;

	struct TestCommand {
		id: &'static str,
		text: &'static str,
	}

	impl Command for TestCommand {
		fn id(&self) -> &'static str {
			self.id
		}

		fn execute(
			&self,
			_doc: &Document,
			_selection: Selection,
			_event: &EditorEvent,
		) -> Option<Transaction> {
			Some(Transaction::new().push(Operation::insert(Position::zero(), self.text)))
		}
	}

	struct TestRule {
		id: &'static str,
		text: &'static str,
	}

	impl InputRule for TestRule {
		fn id(&self) -> &'static str {
			self.id
		}

		fn on_event(
			&self,
			_doc: &Document,
			_selection: Selection,
			_event: &EditorEvent,
		) -> Option<Transaction> {
			Some(Transaction::new().push(Operation::insert(Position::zero(), self.text)))
		}
	}

	struct RecordingHook {
		id: &'static str,
		trace: Arc<Mutex<Vec<String>>>,
	}

	impl TransactionHook for RecordingHook {
		fn id(&self) -> &'static str {
			self.id
		}

		fn before_apply(
			&self,
			_doc: &Document,
			_meta: &TransactionMeta,
			tx: Transaction,
		) -> Transaction {
			self.trace
				.lock()
				.expect("record hook")
				.push(format!("before:{}", self.id));
			tx
		}

		fn after_apply(&self, _doc: &Document, _meta: &TransactionMeta, _tx: &Transaction) {
			self.trace
				.lock()
				.expect("record hook")
				.push(format!("after:{}", self.id));
		}
	}

	#[allow(dead_code)]
	struct TestExtension {
		id: &'static str,
		priority: i32,
		commands: Vec<Box<dyn Command>>,
		rules: Vec<Box<dyn InputRule>>,
		hooks: Vec<Box<dyn TransactionHook>>,
	}

	impl Extension for TestExtension {
		fn id(&self) -> &'static str {
			self.id
		}

		fn priority(&self) -> i32 {
			self.priority
		}

		fn commands(&self) -> Vec<Box<dyn Command>> {
			self.commands
				.iter()
				.map(|c| {
					Box::new(TestCommand {
						id: c.id(),
						text: "",
					}) as Box<dyn Command>
				})
				.collect()
		}

		fn input_rules(&self) -> Vec<Box<dyn InputRule>> {
			self.rules
				.iter()
				.map(|r| {
					Box::new(TestRule {
						id: r.id(),
						text: "",
					}) as Box<dyn InputRule>
				})
				.collect()
		}

		fn transaction_hooks(&self) -> Vec<Box<dyn TransactionHook>> {
			Vec::new()
		}
	}

	#[test]
	fn command_order_is_deterministic_by_priority_then_id() {
		struct ExtA;
		impl Extension for ExtA {
			fn id(&self) -> &'static str {
				"a"
			}

			fn priority(&self) -> i32 {
				1
			}

			fn commands(&self) -> Vec<Box<dyn Command>> {
				vec![Box::new(TestCommand {
					id: "cmd",
					text: "a",
				})]
			}
		}
		struct ExtB;
		impl Extension for ExtB {
			fn id(&self) -> &'static str {
				"b"
			}

			fn priority(&self) -> i32 {
				2
			}

			fn commands(&self) -> Vec<Box<dyn Command>> {
				vec![Box::new(TestCommand {
					id: "cmd",
					text: "b",
				})]
			}
		}

		let runtime = ExtensionRuntime::new(vec![Box::new(ExtA), Box::new(ExtB)]);
		let doc = Document::new();
		let tx = runtime
			.run_commands(
				&doc,
				Selection::collapsed(Position::zero()),
				&EditorEvent::Focus,
			)
			.expect("transaction");

		assert_eq!(tx.meta.origin(), "b");
		assert_eq!(tx.meta.command(), Some("cmd"));
	}

	#[test]
	fn input_rule_order_is_deterministic_by_priority_then_id() {
		struct ExtA;
		impl Extension for ExtA {
			fn id(&self) -> &'static str {
				"a"
			}

			fn priority(&self) -> i32 {
				5
			}

			fn input_rules(&self) -> Vec<Box<dyn InputRule>> {
				vec![Box::new(TestRule {
					id: "rule",
					text: "a",
				})]
			}
		}
		struct ExtB;
		impl Extension for ExtB {
			fn id(&self) -> &'static str {
				"b"
			}

			fn priority(&self) -> i32 {
				5
			}

			fn input_rules(&self) -> Vec<Box<dyn InputRule>> {
				vec![Box::new(TestRule {
					id: "rule",
					text: "b",
				})]
			}
		}

		let runtime = ExtensionRuntime::new(vec![Box::new(ExtB), Box::new(ExtA)]);
		let doc = Document::new();
		let tx = runtime
			.run_input_rules(
				&doc,
				Selection::collapsed(Position::zero()),
				&EditorEvent::Focus,
			)
			.expect("transaction");

		assert_eq!(tx.meta.origin(), "a");
		assert_eq!(tx.meta.input_rule(), Some("rule"));
	}

	#[test]
	fn hooks_run_in_deterministic_order_and_wrap_apply() {
		#[allow(dead_code)]
		struct HookExt {
			id: &'static str,
			priority: i32,
			hook: Box<dyn TransactionHook>,
		}
		impl Extension for HookExt {
			fn id(&self) -> &'static str {
				self.id
			}

			fn priority(&self) -> i32 {
				self.priority
			}

			fn transaction_hooks(&self) -> Vec<Box<dyn TransactionHook>> {
				vec![Box::new(RecordingHook {
					id: self.hook.id(),
					trace: Arc::new(Mutex::new(Vec::new())),
				})]
			}
		}

		let trace = Arc::new(Mutex::new(Vec::new()));
		struct Ext1 {
			trace: Arc<Mutex<Vec<String>>>,
		}
		impl Extension for Ext1 {
			fn id(&self) -> &'static str {
				"a"
			}

			fn priority(&self) -> i32 {
				1
			}

			fn transaction_hooks(&self) -> Vec<Box<dyn TransactionHook>> {
				vec![Box::new(RecordingHook {
					id: "h1",
					trace: self.trace.clone(),
				})]
			}
		}
		struct Ext2 {
			trace: Arc<Mutex<Vec<String>>>,
		}
		impl Extension for Ext2 {
			fn id(&self) -> &'static str {
				"b"
			}

			fn priority(&self) -> i32 {
				2
			}

			fn transaction_hooks(&self) -> Vec<Box<dyn TransactionHook>> {
				vec![Box::new(RecordingHook {
					id: "h2",
					trace: self.trace.clone(),
				})]
			}
		}

		let runtime = ExtensionRuntime::new(vec![
			Box::new(Ext1 {
				trace: trace.clone(),
			}),
			Box::new(Ext2 {
				trace: trace.clone(),
			}),
		]);
		let mut doc = Document::new();
		let tx = RuntimeTransaction {
			meta: TransactionMeta::new("test"),
			transaction: Transaction::new().push(Operation::insert(Position::zero(), "x")),
		};

		runtime.apply_with_hooks(&mut doc, tx);

		assert_eq!(doc.plain_text(), "x");
		let trace = trace.lock().expect("trace").clone();
		assert_eq!(
			trace,
			vec![
				"before:h2".to_string(),
				"before:h1".to_string(),
				"after:h2".to_string(),
				"after:h1".to_string(),
			]
		);
	}
}
