# Configuration for cargo-deny
# See https://embarkstudios.github.io/cargo-deny/

[graph]
targets = []
all-features = true
exclude = ["canvist_book", "canvist_test"]

[advisories]
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/rustsec/advisory-db"]

[licenses]
allow = [
	"MIT",
	"Apache-2.0",
	"BSD-2-Clause",
	"BSD-3-Clause",
	"ISC",
	"Unlicense",
	"Zlib",
	"Unicode-3.0",
	"BSL-1.0",
	"CC0-1.0",
	"MIT-0",
	"Unicode-DFS-2016",
	"OpenSSL",
]
confidence-threshold = 0.8

[bans]
multiple-versions = "warn"
wildcards = "deny"
highlight = "all"

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []
