name: devenv
description: "Setup development environment with devenv"
inputs:
  github-token:
    description: Provide a github token
    required: true
  cache-version:
    description: The version of the cache to use.
    required: false
    default: "v1"

runs:
  using: composite
  steps:
    - name: free disk space
      shell: bash
      run: |
        sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc /opt/hostedtoolcache/CodeQL
        sudo docker image prune --all --force || true
        df -h /

    - name: cache rust dependencies
      uses: Swatinem/rust-cache@v2
      with:
        prefix-key: "${{ inputs.cache-version }}"

    - name: cache cargo binaries
      uses: actions/cache@v4
      with:
        path: ./.bin
        key: ${{ runner.os }}-cargo-bin-${{ inputs.cache-version }}-${{ env.RUSTUP_TOOLCHAIN }}-${{ hashFiles('rust-toolchain.toml', 'Cargo.toml') }}
        restore-keys: |
          ${{ runner.os }}-cargo-bin-${{ inputs.cache-version }}-

    - name: install nix
      uses: cachix/install-nix-action@v31
      with:
        github_access_token: ${{ inputs.github-token }}

    - name: install devenv
      run: |
        nix profile install --accept-flake-config github:cachix/devenv/latest
      shell: bash

    - name: cache devenv
      uses: cachix/cachix-action@v15
      with:
        name: devenv

    - name: install dependencies
      run: cargo bin --install || true
      shell: devenv shell -- bash -e {0}
